version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build steps...
      - npm run lint
  build:
    commands:
      - echo Running build steps...
      - npm run build
  post_build:
    commands:
      - echo Running post-build steps...
      - npm run test

artifacts:
  files:
    - '**/*'
  discard-paths: yes
